### ISSUE TITLE
NameError: name 'get_ipython' is not defined while importing deep_xf

### ISSUE THREAD

**Issue by ahbon123** [ajayarunachalam/Deep_XF#2]
Hello, I imported `deep_xf` and got the error `NameError: name 'get_ipython' is not defined`. I imported from IPython import get_ipython`, but I still got the error. How to solve it?

```
from IPython import get_ipython
from deep_xf.main import *
from deep_xf.dpp import *
from deep_xf.forecast_ml import *
from deep_xf.forecast_ml_extension import *
from deep_xf.stats import *
from deep_xf.utility import *
from deep_xf.denoise import *
from deep_xf.similarity import *
```
An error was returned:

```
Traceback (most recent call last):
   File "/Users/x/Documents/smart_steps/Industrial Operation Index/utils/DeepXF_test.py", line 2, in <module>
     from deep_xf.main import *
   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/deep_xf/__init__.py", line 2, in <module>
     from . import main
   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/deep_xf/main.py", line 14, in <module>
     from .utility import *
   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/deep_xf/utility.py", line 27, in <module>
     get_ipython().run_line_magic('matplotlib', 'inline')
NameError: name 'get_ipython' is not defined
```

**Comment by ajayarunachalam** [comment]
Try upgrading the IPython module something like this - pip3 install --upgrade ipython. This has no dependency on the deep_xf package as far as I remember.
